import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CLI_PACKAGE_JSON = resolve(__dirname, "..", "package.json");
const OUTPUT_PATH = resolve(
  __dirname,
  "..",
  "src",
  "generated",
  "ast-grep-rule-schema.json"
);

// Read @ast-grep/cli version from package.json
const packageJson = JSON.parse(readFileSync(CLI_PACKAGE_JSON, "utf8")) as {
  dependencies?: Record<string, string>;
};
const rawVersion = packageJson.dependencies?.["@ast-grep/cli"];
if (!rawVersion) {
  throw new Error(
    "@ast-grep/cli not found in packages/cli/package.json dependencies"
  );
}

// Strip semver range prefix (^, ~, >=, etc.)
const version = rawVersion.replace(/^[^\d]*/, "");
const sourceUrl = `https://raw.githubusercontent.com/ast-grep/ast-grep/${version}/schemas/rule.json`;

console.log(`Fetching ast-grep rule schema for version ${version}...`);
console.log(`  URL: ${sourceUrl}`);

let response: Response;
try {
  response = await fetch(sourceUrl);
} catch (error) {
  throw new Error(
    `Failed to fetch schema: ${error instanceof Error ? error.message : String(error)}`
  );
}

if (!response.ok) {
  if (existsSync(OUTPUT_PATH)) {
    console.error("  Existing schema file preserved.");
  }
  throw new Error(
    `HTTP ${String(response.status)} fetching schema from ${sourceUrl}`
  );
}

const schema = (await response.json()) as Record<string, unknown>;

// Add metadata comment
schema["$comment"] =
  `Generated by fetch-ast-grep-schema.ts at ${new Date().toISOString()} from ast-grep v${version} (${sourceUrl})`;

writeFileSync(OUTPUT_PATH, JSON.stringify(schema, null, 2) + "\n", "utf8");
console.log(`  Written to: ${OUTPUT_PATH}`);
